### ISSUE TITLE
provide a method to catch an error thrown from the api

### ISSUE THREAD

**Issue by zhenyanghua** [albburtsev/talaria#10]
When aborting requests, the api throws an aborting error which will showup in the client side console, because the error is thrown from the api source, the client app cannot catch and handle it. Could you add a wrapper to the api source to handle the error message as part of a response json to the client?

**Comment by albburtsev** [comment]
Hi!

> because the error is thrown from the api source, the client app cannot catch and handle it

I don't throw error manually in code. I just call `reject` within promise. So, you could handle this error in `catch` block:

```js
api
    .get('users/')
    .catch((error) => {
        // Handle error here
    });
```

> Could you add a wrapper to the api source to handle the error message as part of a response json to the client?

Could you create pull request with your solution of this problem?

Thank you!
