### ISSUE TITLE
Must "handleResponse" return XHR?

### ISSUE THREAD

**Issue by yairEO** [albburtsev/talaria#17]
In my situation I have a React app, with Redux, so I have one file handles the actions, which calls another file which handles the services calls. 

Currently I use **fetch** so the _services_ file returns a promise that the _actions_ file handles and distributes to Redux.  I need to return some custom error Object from the _services_ but I don't know how to do that using your way, since there's not much documentation.

This is my handler as it is now:

```
import { userService } from './user.service';

/**
 * Pre-proccess each request to make sure the user's token is valid
 */
export default function handleResponse( response ){
    return response.text().then(text => {
        const data = text && JSON.parse(text);

        if( !response.ok ){
            if( response.status === 401 ){
                // auto logout if 401 response returned from api
                userService.logout();
                // window.location.reload(true);
            }

            const error = (data && data.message) || {text:response.statusText, status:response.status};
            return Promise.reject(error);
        }

        return data;
    });
}
```

And is used like this:

```
return fetch(query, requestOptions)
     .then(handleResponse)
```

Since I want to work with `fetch-please` I've changed things to look like:

```
const API = new FetchPlease(BASEURL, {
    timeout : 10000, // 3s
    headers : authHeader(),
    handleResponse(xhr) {
        if( xhr.status !== 200 ){
            if( response.status === 401 ){
                userService.logout();
            }

            const error = (data && data.message) || {text:response.statusText, status:response.status};
            ... What should I do with the error.... ?
        }

        return xhr;
    }
});
```

But I have no idea what function/promise/object will actually use `handleResponse` in your `FetchPlease` script, so I don't know what should I do with the error.. should I return it? and where/what will read it?

**Comment by albburtsev** [comment]
>  What should I do with the error.... ?

Just throw it. You know, like:

```js
throw new Error('Error message here')
```
