### ISSUE TITLE
Query string strips false values

### ISSUE THREAD

**Issue by Zashy** [albburtsev/talaria#2]
The joinParams helper function strips false query string parameters.

Maybe I should be more disciplined and use strings in the params object. Was doing the following:

`api.getRequest('/api', {id: "10", process: false});`

after that the the XHR's url is /api?id=10
but it should be: /api?id=10&process=false

**Comment by albburtsev** [comment]
Let's take a look on [jQuery.param](http://api.jquery.com/jQuery.param/) as example a good query serialization:

``` js
jQuery.param({a: 1, b: 2}); // "a=1&b=2"
jQuery.param({a: 1, b: undefined}); // "a=1&b="
jQuery.param({a: 1, b: false}); // "a=1&b=false"
jQuery.param({a: 1, b: null}); // "a=1&b="
```

I will implement same behaviour soon.
